### ISSUE TITLE
asynchron Mautic Event handling is not working

### ISSUE THREAD

**Issue by pety-dc** [kuzmany/mautic-recommender-bundle#10]
I uploaded an inventory and tried to send events of `RecommendEvent` type as described on https://docs.mtcextendee.com/installation/tracking

The `mt('send', 'RecommenderEvent', { eventName: 'DetailView', itemId:'9-191' });` function was called in a handler of a JS click event. I experienced that the recommender plugin did not receive the events this way.

I tried to trace the error and concluded that the event handler code (MauticJs.recommenderWevent) in `MauticRecommenderBundle/EventListener/BuildJsSubscriber.php` is half wrong:

The recommenderEvent function looks like this:

```
MauticJS.recommenderEvent = function (params) {
        parms = {};
        var eventParams = {};

          if (typeof MauticJS.getInput === 'function') {
                queue = MauticJS.getInput('send', '{$eventLabel}');
            } else {
                return false;
            }
            if (queue) {
                for (var i=0; i<queue.length; i++) {
                    var event = queue[i];
                    // Merge user defined tracking pixel parameters.
                    if (typeof event[2] === 'object') {
                        for (var attr in event[2]) {
                            eventParams[attr] = event[2][attr];
                        }
                        parms['eventDetail'] = btoa(JSON.stringify(eventParams));
                        parms['params'] = btoa(unescape(encodeURIComponent(JSON.stringify(params.params))));
                    }
   
                    MauticJS.makeCORSRequest('POST', '{$url}', parms,.
                        function(response) {
                        },
                        function() {

                    });
    
       }
                  }
            }

document.addEventListener('eventAddedToMauticQueue', function(e) {
      if(e.detail[0] == 'send' && e.detail[1] == '{$eventLabel}'){
         MauticJS.recommenderEvent();
      }
    });

```

The function get an argument `params` then doesn't handle it ever, but always tries to get the events via `MauticJS.getInput` function call.

But as far as I understood the core mautic code, the BuildJSSubscriber in CoreBundle overrides how `mt` function calls  are handled after mtc.js is loaded: instead of putting the new mautic events into a queue, the mautic events are dispatched immediately as `eventAddedToMauticQueue` JS event for subscribers to handle.

```
// Dispatch the queue event when an event is added to the queue
    if (!MauticJS.inputQueue.hasOwnProperty('push')) {
        Object.defineProperty(MauticJS.inputQueue, 'push', {
            configurable: false,
            enumerable: false,
            writable: false,
            value: function () {
                for (var i = 0, n = this.length, l = arguments.length; i < l; i++, n++) {
                    MauticJS.dispatchEvent('eventAddedToMauticQueue', arguments[i]);
                }
                return n;
            }
        });
    }
```

The recommender Plugin subscribes to this JS event and `MauticJS.recommenderEvent();` is called, but `MauticJS.recommenderEvent();` tries to get the event details from the queue instead of the argument.

So the result is that when the recommender event (`mt('send', 'RecommenderEvent', { eventName: 'DetailView', itemId:'9-191' });`) is called before mtc.js is loaded, it works perfectly, but when the function is called after mtc.js is loaded, it fails.

As a good example pageviews are handled like this:

```
m.sendPageview = function(pageview) {
        var queue = [];

        if (!pageview) {
            if (typeof m.getInput === 'function') {
                queue = m.getInput('send', 'pageview');
            } else {
                return false;
            }
        } else {
            queue.push(pageview);
        }

        if (queue) {
[...]         
```

**Comment by kuzmany** [comment]
Trackin require this PR https://github.com/mautic/mautic/pull/6782

**Comment by pety-dc** [comment]
According to the diff that only prevents any kind of mt() call to be handled as a pageview event. Event handling is not exclusive I suppose so calling `mt('send', 'RecommenderEvent', { eventName: 'DetailView', itemId:'9-191' });` should trigger the original Mautic code to handle it as a pageview, but should not prevent the recommender's own event handler to run.

I believe that's not the issue here.

Meanwhile I changed the event handler code to be similar to the `m.sendPageview` and it worked:

```
MauticJS.recommenderEvent = function (params) {
  parms = {};
  var eventParams = {};
  var queue = [];

  if (!params) {
    if (typeof MauticJS.getInput === 'function') {
      queue = MauticJS.getInput('send', '{$eventLabel}');
    } else {
      return false;
    }
  } else {
    queue.push(params);
  }
  
  if (queue) {
    for (var i=0; i<queue.length; i++) {
      var event = queue[i];
      if (event[0] == 'send' && event[1] == '{$eventLabel}'){
        // Merge user defined tracking pixel parameters.
        if (typeof event[2] === 'object') {
          for (var attr in event[2]) {
            eventParams[attr] = event[2][attr];
          }
          parms['eventDetail'] = btoa(JSON.stringify(eventParams));
          parms['params'] = btoa(unescape(encodeURIComponent(JSON.stringify(params.params))));
        }
        MauticJS.makeCORSRequest('POST', '{$url}', parms,.
                    function(response) {
                    },
                    function() {

                });
        }
       }
                  }
            }
```

However I also had to ensure event context during the processing of the `queue` variable as 
```
MauticJS.onFirstEventDelivery(MauticJS.recommenderEvent);
```
triggers the call of `MauticJS.recommenderEvent` with the first mautic event regardless of type.

**Comment by kuzmany** [comment]
Thank you! https://github.com/kuzmany/mautic-recommender-bundle/pull/11
