### ISSUE TITLE
recommender order by SQL error

### ISSUE THREAD

**Issue by pety-dc** [kuzmany/mautic-recommender-bundle#12]
Hey,

I'm still trying to figure out how the recommandation is supposed to work. But I ran into some SQL errors while the plugin tried to assemble the recommendation in a campaign.

The cause of the error might originate from the order by settings I applied.

![FireShot Capture 073 - Edit pety-proba](https://user-images.githubusercontent.com/25766885/56361531-e9d68300-61e7-11e9-9619-a26df35c5e31.png)

For these settings I got the following error:

```
[2019-04-16 15:53:12] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'SELECT l.item_id as id FROM recommender_event_log l WHERE (l.lead_id = ?) AND (EXIS
TS(SELECT NULL FROM recommender_item_property_value lItxUpBS WHERE (lItxUpBS.item_id = l.item_id) AND (lItxUpBS.property_id = 3) AND (lItxUpBS.value = ?))) GROUP BY l.i
tem_id ORDER BY SUM(.weight) DESC LIMIT 6' with params [138526, "indukci\u00f3s"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQ
L syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') DESC LIMIT 6' at line 1 [] []
```

First of all the table name is missing from order by clause. 
But the query also lacks a table with `weight` field. 

Either the `recommender_events` table should be joined, or performance-wise it would be a better solution to store the weights of the events in the `recommender_event_log` records.

**Comment by pety-dc** [comment]
Hey @kuzmany, 
I begin fixing these issues. And while I was doing that I gave some time to think about how recommendations and filtering works. I can think of how I would do a recommender that does the `Abandoned cart` feature, but I'm still missing something for `Customers who bought items in your cart also bought`

I could filter which items have `cart` event for the current user, but I can't figure out how I could cross-filter it to get items that other contacts have `bought` event for who also have `bought` event for the item the current user has `cart` event  for.

Am I missing a special `type of recommendations` besides filters?

**Comment by pety-dc** [comment]
Hey @kuzmany 
I'm not asking you to tell me how to do those features that are listed in the readme. I'm just asking whether can be done in the plugin's current form, or they require some non-public extension?

**Comment by kuzmany** [comment]
Hi, filters are inspirated by Segments filters https://github.com/mautic/mautic/pull/5755
Share some of code, query generator is very similar.

**Comment by kuzmany** [comment]
We use two types of filters:
- filters for segments https://github.com/kuzmany/mautic-recommender-bundle/tree/master/Filter/Segment
- filters for recommendations https://github.com/kuzmany/mautic-recommender-bundle/tree/master/Filter/Recommender

**Comment by pety-dc** [comment]
@kuzmany 
Thanks

But still I must ask you how you would create a recommendation with these filters/tools for the following scenario:
I contact browses your webpage and does sends in recommendation events (eg: purchaseed something) I know how to create a recommender that recommends items specifically to that user. 
But how would you create a recommender that recommends to each user that purchased something, other items that others who also purchased that item, also purchased?

**Comment by kuzmany** [comment]
@pety-dc I didn't finished that part.
My idea was something like this https://github.com/mautic/mautic/pull/7424 with another changes. That means, the query in one path should communicate between them self.
But any way,  If you need fast solution you can add with plugin  your own filters

![image](https://user-images.githubusercontent.com/462477/58870465-85508400-86c0-11e9-816d-ff9bd1c2351a.png)

There are listener

RecommenderEvents::ON_RECOMMENDER_FILTER_FORM_CHOICES_GENERATE - you can add new option to filters select box
RecommenderEvents::ON_RECOMMENDER_FILTER_RESULTS - you can detect If this filter was selected and make own query to query builder

Maybe should be better way.
