### ISSUE TITLE
Can't create a New Recommender

### ISSUE THREAD

**Issue by ccorbalan** [kuzmany/mautic-recommender-bundle#21]
Hi,

We've installed Mautic v2.15.1 with PHP 7.0.33. We've installed and enabled the plug-in following the steps without any problem. We've create some Events, Import Items and create a Template. We can see all this information in Recommender tables in the data madel but when we try to create a new Recommender nothing happens.

This is the complete message in the Mautic log file:

[2019-07-31 21:16:38] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)" at /var/www/html/mautic/plugins/MauticRecommenderBundle/Form/Type/RecommenderTableOrderType.php line 150 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /var/www/html/mautic/plugins/MauticRecommenderBundle/Form/Type/RecommenderTableOrderType.php:150)"} []

![datamodel_image](https://user-images.githubusercontent.com/23479343/62241496-8f99b080-b3d9-11e9-84a3-a2530194feb6.PNG)
![Events](https://user-images.githubusercontent.com/23479343/62241498-90324700-b3d9-11e9-8b0b-800d5200dd11.PNG)
![creating_new_recommender](https://user-images.githubusercontent.com/23479343/62241501-90324700-b3d9-11e9-956a-d7528c5814f5.PNG)

Please, let me know if you need more info.

Regards,

**Comment by kuzmany** [comment]
What PHP version?

**Comment by ccorbalan** [comment]
PHP version 7.0.33. An image is attached
![php_version](https://user-images.githubusercontent.com/23479343/62244864-9c6dd280-b3e0-11e9-88fe-81515e533333.PNG)

**Comment by kuzmany** [comment]
Ok, this is CLI PHP version. 
What about yourmauticurl.com/s/sysinfo ?

**Comment by kuzmany** [comment]
Require PHP 7.1 and higher. 
I will add this info to documentation.

**Comment by ccorbalan** [comment]
Thank you very much. The problem has been solved updating to 7.1

**Comment by ccorbalan** [comment]
Hi,

I'm testing the plug-in and I'm trying to automate the update of items from
e-commerce platform. We are working with Magento and we use the Simple
Google Shopping extension to have the feed of products because it's easy to
integrate with other platforms. Have you used it before?

I'm thinking to transofrm the ouput (in xml format) to the json format
needed by the plug-in...

Thank you very much.

Carlos

**Comment by kuzmany** [comment]
You can create own xml to JSON convertor. 
Or you can hire me add support to XML format
