### ISSUE TITLE
Error importing items.json file

### ISSUE THREAD

**Issue by Ritla** [kuzmany/mautic-recommender-bundle#22]
When trying to upload items.json through command php app/console mautic:recommender:import --type=items  --file="http://domain.tld/path/to/items.json" as defined in instruction giving error as below:

[Symphony\Component\Debug\Exception\ClassNotFoundException]
Attempted to load class "JsonMachine" from namespace "JsonMachine".
Did you forget a "use" statement for another namespace?

mautic: recommender: import [-t|--type TYPE] [-f|--file [FILE]] [-1|--batchlimit[BATCH-LIMIT]] [-timeout [TIMEOUT]] [-h| --help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

And when executing console mautic:recommender:import --type=items --file="https://domain.tld/path/to/items.json" --batch-limit=100 --timeout=-1 day

Get error as below:

[Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "command".       
                                                          
mautic:recommender:import [-t|--type TYPE] [-f|--file [FILE]] [-l|--batch-limit [BATCH-LIMIT]] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] 

Using Mautic 2.15.1   PHP - 7.2

Thanks

**Comment by Ritla** [comment]
Below is the error from the mautic log when import items.json

[2019-09-18 03:15:01] mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'JsonMachine\JsonMachine' not found (uncaught exception) at /home/usermane/public_html/folder/plugins/MauticRecommenderBundle/Command/PushDataToRecommenderCommand.php line 164 while running console command `mautic:recommender:import` [] []

**Comment by kuzmany** [comment]
What is not clear? 
You didn't install it by composer `composer require kuzmany/mautic-recommender-bundle`
Bundle require halaxa/json-machine library https://github.com/kuzmany/mautic-recommender-bundle/blob/master/composer.json
