### ISSUE TITLE
recommender content in email

### ISSUE THREAD

**Issue by pety-dc** [kuzmany/mautic-recommender-bundle#24]
Hey

I recently tested the recommender plugin in email and noticed that gmail completely screws up the template. 

It's due to the fact that the recommender template consists of a <style> and a html structure: <div>-s decorated with classes.
Gmail actually scraps the <style> tag and removes the classes from the divs.

Do you happened to run into the same issue?

It seems to me that the scructure needs to be changed from <style> and classes to inline style attributes.

**Comment by kuzmany** [comment]
Email template don't use div elements, but yes. 
All styles are in `<style>`. At that time I didn't notice gmail remove it.
Maybe we can process code with css to inline
