### ISSUE TITLE
When deactivated, the plugin created errors on merging contacts. 

### ISSUE THREAD

**Issue by MajesteitBart** [kuzmany/mautic-recommender-bundle#26]
When on contacts entered forms on multiple devices, the plugin (even when deactivated) prevented contacts from merging. Threw this error:

`[2020-02-27 17:01:14] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to MauticPlugin\MauticRecommenderBundle\EventListener\LeadSubscriber::onLeadMerge() must be an instance of MauticPlugin\MauticRecommenderBundle\EventListener\LeadMergeEvent, instance of Mautic\LeadBundle\Event\LeadMergeEvent given" at /opt/bitnami/apps/mautic/htdocs/plugins/MauticRecommenderBundle/EventListener/LeadSubscriber.php line 120 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to MauticPlugin\\MauticRecommenderBundle\\EventListener\\LeadSubscriber::onLeadMerge() must be an instance of MauticPlugin\\MauticRecommenderBundle\\EventListener\\LeadMergeEvent, instance of Mautic\\LeadBundle\\Event\\LeadMergeEvent given at /opt/bitnami/apps/mautic/htdocs/plugins/MauticRecommenderBundle/EventListener/LeadSubscriber.php:120)"} []`

**Comment by kuzmany** [comment]
This should be already fixed in master branch
