### ISSUE TITLE
Recommmender bundle installation issue 

### ISSUE THREAD

**Issue by raghav111jain** [kuzmany/mautic-recommender-bundle#27]
mautic 3.0
php 7.2

in cpanel run this 
"COMPOSER_MEMORY_LIMIT=-1 Composer require kuzmany/mautic-recommender-bundle"
check this img 

![image](https://user-images.githubusercontent.com/53876757/85568633-792ec000-b64f-11ea-8c26-befd6ab4e0b5.png)

**Comment by kuzmany** [comment]
Plugin is not M3 compatible
